update=lun 17 jun 2013 20:16:22 CEST
last_client=pcbnew
[common]
NetDir=
[cvpcb]
version=1
NetIExt=net
[cvpcb/libraries]
EquName1=devcms
[general]
version=1
[eeschema]
version=1
LibDir=
NetFmtName=
RptD_X=0
RptD_Y=100
RptLab=1
LabSize=60
[eeschema/libraries]
LibName1=/home/carlosgs/GitRepos/GNBot/Electronics/KicadLibs/RaronLibs/LED_RGB/LED_RGB
LibName2=/home/carlosgs/GitRepos/GNBot/Electronics/KicadLibs/VREG/vreg
LibName3=/home/carlosgs/GitRepos/GNBot/Electronics/KicadLibs/Arduino_Shield_Modules_for_KiCad_V3/arduino_shieldsNCL
LibName4=power
LibName5=device
LibName6=transistors
LibName7=conn
LibName8=linear
LibName9=regul
LibName10=74xx
LibName11=cmos4000
LibName12=adc-dac
LibName13=memory
LibName14=xilinx
LibName15=special
LibName16=microcontrollers
LibName17=dsp
LibName18=microchip
LibName19=analog_switches
LibName20=motorola
LibName21=texas
LibName22=intel
LibName23=audio
LibName24=interface
LibName25=digital-audio
LibName26=philips
LibName27=display
LibName28=cypress
LibName29=siliconi
LibName30=opto
LibName31=atmel
LibName32=contrib
LibName33=valves
[pcbnew]
version=1
LastNetListRead=
UseCmpFile=1
PadDrill="    0,700000"
PadDrillOvalY="    0,700000"
PadSizeH="    1,500000"
PadSizeV="    2,000000"
PcbTextSizeV="    2,032000"
PcbTextSizeH="    1,524000"
PcbTextThickness="    0,304800"
ModuleTextSizeV="    1,524000"
ModuleTextSizeH="    1,524000"
ModuleTextSizeThickness="    0,304800"
SolderMaskClearance="    0,200000"
SolderMaskMinWidth="    0,000000"
DrawSegmentWidth="    0,381000"
BoardOutlineThickness="    2,400000"
ModuleOutlineThickness="    0,381000"
[pcbnew/libraries]
LibDir=
LibName1=/home/carlosgs/GitRepos/GNBot/Electronics/KicadLibs/switch_largePads
LibName2=/home/carlosgs/GitRepos/GNBot/Electronics/KicadLibs/button_largePads
LibName3=/home/carlosgs/GitRepos/GNBot/Electronics/KicadLibs/kicad_diy_modules/diy_diodes
LibName4=/home/carlosgs/GitRepos/GNBot/Electronics/KicadLibs/RaronLibs/LED_RGB/LED5_RGB
LibName5=/home/carlosgs/GitRepos/GNBot/Electronics/KicadLibs/Arduino_Shield_Modules_for_KiCad_V3/arduino_shields
LibName6=/home/carlosgs/GitRepos/GNBot/Electronics/KicadLibs/VREG/v-reg
LibName7=/home/carlosgs/GitRepos/GNBot/Electronics/KicadLibs/BW_Chokes/Choke_Toroid_ThroughHole_RevB_06Aug2010/Choke_Toroid_ThroughHole_RevB_06Aug2010
LibName8=sockets
LibName9=connect
LibName10=discret
LibName11=pin_array
LibName12=divers
LibName13=libcms
LibName14=display
LibName15=valves
LibName16=led
LibName17=dip_sockets
