update=jue 13 jun 2013 15:55:28 CEST
last_client=eeschema
[common]
NetDir=
[cvpcb]
version=1
NetIExt=net
[cvpcb/libraries]
EquName1=devcms
[pcbnew]
version=1
LastNetListRead=
UseCmpFile=1
PadDrill="    1,000000"
PadDrillOvalY="    1,000000"
PadSizeH="    1,100000"
PadSizeV="    1,700000"
PcbTextSizeV="    2,032000"
PcbTextSizeH="    1,524000"
PcbTextThickness="    0,304800"
ModuleTextSizeV="    1,524000"
ModuleTextSizeH="    1,524000"
ModuleTextSizeThickness="    0,304800"
SolderMaskClearance="    0,200000"
SolderMaskMinWidth="    0,000000"
DrawSegmentWidth="    0,381000"
BoardOutlineThickness="    0,381000"
ModuleOutlineThickness="    0,381000"
[pcbnew/libraries]
LibDir=
LibName1=/home/carlosgs/GitRepos/GNBot/Electronics/KicadLibs/kicad_diy_modules/diy_diodes
LibName2=/home/carlosgs/GitRepos/GNBot/Electronics/KicadLibs/RaronLibs/LED_RGB/LED5_RGB
LibName3=/home/carlosgs/GitRepos/GNBot/Electronics/KicadLibs/Arduino_Shield_Modules_for_KiCad_V3/arduino_shields
LibName4=/home/carlosgs/GitRepos/GNBot/Electronics/KicadLibs/VREG/v-reg
LibName5=/home/carlosgs/GitRepos/GNBot/Electronics/KicadLibs/BW_Chokes/Choke_Toroid_ThroughHole_RevB_06Aug2010/Choke_Toroid_ThroughHole_RevB_06Aug2010
LibName6=sockets
LibName7=connect
LibName8=discret
LibName9=pin_array
LibName10=divers
LibName11=libcms
LibName12=display
LibName13=valves
LibName14=led
LibName15=dip_sockets
[general]
version=1
[eeschema]
version=1
LibDir=
NetFmtName=
RptD_X=0
RptD_Y=100
RptLab=1
LabSize=60
[eeschema/libraries]
LibName1=/home/carlosgs/GitRepos/GNBot/Electronics/KicadLibs/RaronLibs/LED_RGB/LED_RGB
LibName2=/home/carlosgs/GitRepos/GNBot/Electronics/KicadLibs/VREG/vreg
LibName3=/home/carlosgs/GitRepos/GNBot/Electronics/KicadLibs/Arduino_Shield_Modules_for_KiCad_V3/arduino_shieldsNCL
LibName4=power
LibName5=device
LibName6=transistors
LibName7=conn
LibName8=linear
LibName9=regul
LibName10=74xx
LibName11=cmos4000
LibName12=adc-dac
LibName13=memory
LibName14=xilinx
LibName15=special
LibName16=microcontrollers
LibName17=dsp
LibName18=microchip
LibName19=analog_switches
LibName20=motorola
LibName21=texas
LibName22=intel
LibName23=audio
LibName24=interface
LibName25=digital-audio
LibName26=philips
LibName27=display
LibName28=cypress
LibName29=siliconi
LibName30=opto
LibName31=atmel
LibName32=contrib
LibName33=valves
